### ISSUE TITLE
Request for Symfony 5.4 Compatibility and Release of a Stable Version

### ISSUE THREAD

**Issue by chiqui3d** [williarin/cook#4]
Hello,

1. Compatibility with **Symfony 5.4**: Currently, I am working on a project that uses Symfony 5.4. I've found your package to be quite useful and would love to integrate it into my project. However, I noticed that it does not explicitly state compatibility with Symfony 5.4. Could you please confirm if it's compatible with Symfony 5.4 or update it accordingly?

3. Release of a **Stable Version**: When trying to install your package via Composer, I encountered an issue where Composer indicates that the package cannot be installed due to it not matching the minimum-stability requirement (stable). It would be immensely helpful if a stable version of the package could be released.

**Comment by williarin** [comment]
Hello, thank you for your interest in this package!
I've created a 1.0.0 release based on the current commit.

About Symfony 5.4 I haven't tested it, I'll try to test and make necessary changes in the coming weeks. In the meantime if you want to open a PR to address this issue please do so, any help is welcome!
